// packages/vue-better-tweet/src/twitter-theme/tweet-replies.vue
<script setup lang="ts">
import type { EnrichedTweet } from 'react-tweet'
import { computed } from 'vue'
import { formatNumber } from 'react-tweet'
import s from './tweet-replies.module.css'

type Props = {
  tweet: EnrichedTweet
}

const props = defineProps<Props>()

const label = computed(() => {
  const count = props.tweet.conversation_count
  if (count === 0) return 'Read more on X'
  if (count === 1) return `Read ${formatNumber(count)} reply`
  return `Read ${formatNumber(count)} replies`
})
</script>

<template>
  <div :class="s.replies">
    <a :class="s.link" :href="props.tweet.url" target="_blank" rel="noopener noreferrer">
      <span :class="s.text">{{ label }}</span>
    </a>
  </div>
</template>

// packages/next-tweet/src/tweet-replies.tsx
import type { FC } from 'react'
import type { Tweet } from './api'
import { getTweetUrl, formatNumber } from './utils'
import s from './tweet-replies.module.css'

export const TweetReplies: FC<{ tweet: Tweet }> = ({ tweet }) => (
  <div className={s.replies}>
    <a
      className={s.link}
      href={getTweetUrl(tweet)}
      target="_blank"
      rel="noopener noreferrer"
    >
      <span className={s.text}>
        {tweet.conversation_count > 0
          ? `Read ${formatNumber(tweet.conversation_count)} replies`
          : 'Read more on Twitter'}
      </span>
    </a>
  </div>
)
