// apps/vite-app/src/App.vue
<template>
  <div :class="rootClass">
    <main :class="styles.main">
      <RouterView />
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, useCssModule } from 'vue'
import clsx from 'clsx'
import { RouterView } from 'vue-router'
import './base.css'

const styles = useCssModule()

const rootClass = computed(() => clsx(styles.root, 'react-tweet-theme'))
</script>

<style module src="./layout.module.css"></style>

// apps/vite/src/app.tsx
import clsx from 'clsx'
import { EmbeddedTweet, TweetSkeleton } from 'next-tweet'
import { type Tweet } from 'next-tweet/api'
import useSWR from 'swr'
import styles from './app.module.css'

async function fetcher(url: string) {
  const res = await fetch(url)
  const json = await res.json()
  return json.data
}

function App() {
  const tweetId = '1628832338187636740'
  const { data, error, isLoading } = useSWR<Tweet>(
    `/api/tweet/${tweetId}`,
    fetcher
  )

  return (
    <div data-theme="dark">
      <div className={clsx(styles.root, 'next-tweet-theme')}>
        <main className={styles.main}>
          {isLoading || error || !data ? (
            <TweetSkeleton />
          ) : (
            <EmbeddedTweet tweet={data} />
          )}
        </main>
      </div>
    </div>
  )
}

export default App
