// apps/vite-app/src/pages/tweet.tsx
import { useParams } from 'react-router-dom'
import { EmbeddedTweet, TweetNotFound, TweetSkeleton } from 'react-tweet'
import { type Tweet } from 'react-tweet/api'
import useSWR from 'swr'

async function fetcher(url: string) {
  const res = await fetch(url)
  const json = await res.json()
  return json.data
}

export const TweetPage = () => {
  const params = useParams()
  const { data, error, isLoading } = useSWR<Tweet>(
    // `/api/tweet` does not run locally with the vite server but it will work on Vercel.
    import.meta.env.PROD
      ? `/api/tweet/${params.id}`
      : `https://react-tweet.vercel.app/api/tweet/${params.id}`,
    fetcher
  )

  if (isLoading) return <TweetSkeleton />
  if (error || !data) return <TweetNotFound error={error} />

  return <EmbeddedTweet tweet={data} />
}

// apps/vite-app/src/pages/tweet.vue
<template>
  <TweetSkeleton v-if="isLoading" />
  <TweetNotFound v-else-if="error || !data" :error="errorValue" />
  <EmbeddedTweet v-else :tweet="data" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { EmbeddedTweet, TweetNotFound, TweetSkeleton, useTweet } from 'vue-better-tweet'

const route = useRoute()

const tweetId = computed(() => {
  const id = route.params.id
  return Array.isArray(id) ? id[0] : id
})

const apiUrl = computed(() => {
  if (!tweetId.value) return undefined
  return import.meta.env.PROD
    ? `/api/tweet/${tweetId.value}`
    : `https://react-tweet.vercel.app/api/tweet/${tweetId.value}`
})

const { data, error, isLoading } = useTweet(tweetId, apiUrl)

const errorValue = computed(() => error.value ?? undefined)
</script>
