// packages/vue-better-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-body.vue
<script setup lang="ts">
import type { EnrichedQuotedTweet } from 'react-tweet'
import s from './quoted-tweet-body.module.css'

type Props = {
  tweet: EnrichedQuotedTweet
}

const props = defineProps<Props>()
</script>

<template>
  <p :class="s.root" :lang="props.tweet.lang" dir="auto">
    <span v-for="(item, index) in props.tweet.entities" :key="index" v-html="item.text" />
  </p>
</template>

// packages/react-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-body.tsx
import type { EnrichedQuotedTweet } from '../../utils.js'
import s from './quoted-tweet-body.module.css'

type Props = { tweet: EnrichedQuotedTweet }

export const QuotedTweetBody = ({ tweet }: Props) => (
  <p className={s.root} lang={tweet.lang} dir="auto">
    {tweet.entities.map((item, i) => (
      <span key={i} dangerouslySetInnerHTML={{ __html: item.text }} />
    ))}
  </p>
)
