// packages/react-tweet/src/twitter-theme/quoted-tweet/quoted-tweet.tsx
import type { EnrichedQuotedTweet } from '../../utils.js'
import type { TwitterComponents } from '../types.js'
import { QuotedTweetContainer } from './quoted-tweet-container.js'
import { QuotedTweetHeader } from './quoted-tweet-header.js'
import { QuotedTweetBody } from './quoted-tweet-body.js'
import { TweetMedia } from '../tweet-media.js'

type Props = { tweet: EnrichedQuotedTweet, components?: TwitterComponents }

export const QuotedTweet = ({ tweet, components }: Props) => (
  <QuotedTweetContainer tweet={tweet}>
    <QuotedTweetHeader tweet={tweet} components={components} />
    <QuotedTweetBody tweet={tweet} />
    {tweet.mediaDetails?.length ? <TweetMedia quoted tweet={tweet} /> : null}
  </QuotedTweetContainer>
)

// packages/vue-better-tweet/src/twitter-theme/quoted-tweet/quoted-tweet.vue
<script setup lang="ts">
import type { EnrichedQuotedTweet } from 'react-tweet'
import type { TwitterComponents } from '../types'
import QuotedTweetContainer from './quoted-tweet-container.vue'
import QuotedTweetHeader from './quoted-tweet-header.vue'
import QuotedTweetBody from './quoted-tweet-body.vue'
import TweetMedia from '../tweet-media.vue'

type Props = {
  tweet: EnrichedQuotedTweet
  components?: TwitterComponents
}

const props = defineProps<Props>()
</script>

<template>
  <QuotedTweetContainer :tweet="props.tweet">
    <QuotedTweetHeader :tweet="props.tweet" :components="props.components" />
    <QuotedTweetBody :tweet="props.tweet" />
    <TweetMedia
      v-if="props.tweet.mediaDetails?.length"
      :tweet="props.tweet"
      quoted
      :components="props.components"
    />
  </QuotedTweetContainer>
</template>
