// packages/react-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-header.tsx
import clsx from 'clsx'
import { AvatarImg } from '../avatar-img.js'
import s from './quoted-tweet-header.module.css'
import type { EnrichedQuotedTweet } from '../../utils.js'
import { VerifiedBadge } from '../verified-badge.js'
import { HighlightedLabel } from '../highlighted-label.js'
import type { TwitterComponents } from '../types.js'

type Props = { tweet: EnrichedQuotedTweet; components?: TwitterComponents }

export const QuotedTweetHeader = ({ tweet, components }: Props) => {
  const { user } = tweet
  const Img = components?.AvatarImg ?? AvatarImg

  return (
    <div className={s.header}>
      <a
        href={tweet.url}
        className={s.avatar}
        target="_blank"
        rel="noopener noreferrer"
      >
        <div
          className={clsx(
            s.avatarOverflow,
            user.profile_image_shape === 'Square' && s.avatarSquare
          )}
        >
          <Img
            src={user.profile_image_url_https}
            alt={user.name}
            width={20}
            height={20}
          />
        </div>
      </a>
      <div className={s.author}>
        <div className={s.authorText}>
          <span title={user.name}>{user.name}</span>
        </div>
        <VerifiedBadge user={user} />
        <HighlightedLabel user={user} />
        <div className={s.username}>
          <span title={`@${user.screen_name}`}>@{user.screen_name}</span>
        </div>
      </div>
    </div>
  )
}

// packages/vue-better-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-header.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { EnrichedQuotedTweet } from 'react-tweet'
import clsx from 'clsx'
import type { TwitterComponents } from '../types'
import AvatarImg from '../avatar-img.vue'
import HighlightedLabel from '../highlighted-label.vue'
import VerifiedBadge from '../verified-badge.vue'
import s from './quoted-tweet-header.module.css'

type Props = {
  tweet: EnrichedQuotedTweet
  components?: TwitterComponents
}

const props = defineProps<Props>()
const Img = computed(() => props.components?.AvatarImg ?? AvatarImg)
</script>

<template>
  <div :class="s.header">
    <a :href="props.tweet.url" :class="s.avatar" target="_blank" rel="noopener noreferrer">
      <div :class="clsx(s.avatarOverflow, props.tweet.user.profile_image_shape === 'Square' && s.avatarSquare)">
        <component
          :is="Img"
          :src="props.tweet.user.profile_image_url_https"
          :alt="props.tweet.user.name"
          :width="20"
          :height="20"
        />
      </div>
    </a>
    <div :class="s.author">
      <div :class="s.authorText">
        <span :title="props.tweet.user.name">{{ props.tweet.user.name }}</span>
      </div>
      <VerifiedBadge :user="props.tweet.user" />
      <HighlightedLabel :user="props.tweet.user" />
      <div :class="s.username">
        <span :title="`@${props.tweet.user.screen_name}`">@{{ props.tweet.user.screen_name }}</span>
      </div>
    </div>
  </div>
</template>
