// packages/react-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-container.tsx
'use client'

import type { ReactNode } from 'react'
import type { EnrichedQuotedTweet } from '../../utils.js'
import s from './quoted-tweet-container.module.css'

type Props = { tweet: EnrichedQuotedTweet; children: ReactNode }

export const QuotedTweetContainer = ({ tweet, children }: Props) => (
  <div
    className={s.root}
    onClick={(e) => {
      e.preventDefault()
      window.open(tweet.url, '_blank')
    }}
  >
    <article className={s.article}>{children}</article>
  </div>
)

// packages/vue-better-tweet/src/twitter-theme/quoted-tweet/quoted-tweet-container.vue
<script setup lang="ts">
import type { EnrichedQuotedTweet } from 'react-tweet'
import s from './quoted-tweet-container.module.css'

type Props = {
  tweet: EnrichedQuotedTweet
}

const props = defineProps<Props>()

const handleClick = (event: MouseEvent) => {
  event.preventDefault()
  window.open(props.tweet.url, '_blank')
}
</script>

<template>
  <div :class="s.root" @click="handleClick">
    <article :class="s.article">
      <slot />
    </article>
  </div>
</template>
