// packages/vue-better-tweet/src/twitter-theme/tweet-replies.vue
<script setup lang="ts">
import type { EnrichedTweet } from 'react-tweet'
import { computed } from 'vue'
import { formatNumber } from 'react-tweet'
import s from './tweet-replies.module.css'

type Props = {
  tweet: EnrichedTweet
}

const props = defineProps<Props>()

const label = computed(() => {
  const count = props.tweet.conversation_count
  if (count === 0) return 'Read more on X'
  if (count === 1) return `Read ${formatNumber(count)} reply`
  return `Read ${formatNumber(count)} replies`
})
</script>

<template>
  <div :class="s.replies">
    <a :class="s.link" :href="props.tweet.url" target="_blank" rel="noopener noreferrer">
      <span :class="s.text">{{ label }}</span>
    </a>
  </div>
</template>

// packages/react-tweet/src/tweet-replies.tsx
import { useMemo } from 'react'
import type { Tweet } from './api/index.js'
import { getTweetUrl, formatNumber } from './utils.js'
import s from './tweet-replies.module.css'

export const TweetReplies = ({ tweet }: { tweet: Tweet }) => {
  const repliesLinkText = useMemo(() => {
    if (tweet.conversation_count === 0) return 'Read more on Twitter'

    return tweet.conversation_count === 1
      ? `Read ${formatNumber(tweet.conversation_count)} reply`
      : `Read ${formatNumber(tweet.conversation_count)} replies`
  }, [tweet.conversation_count])

  return (
    <div className={s.replies}>
      <a
        className={s.link}
        href={getTweetUrl(tweet)}
        target="_blank"
        rel="noopener noreferrer"
      >
        <span className={s.text}>{repliesLinkText}</span>
      </a>
    </div>
  )
}
