// packages/vue-better-tweet/src/twitter-theme/tweet-body.vue
<script setup lang="ts">
import type { EnrichedTweet } from 'react-tweet'
import TweetLink from './tweet-link.vue'
import s from './tweet-body.module.css'

type Props = {
  tweet: EnrichedTweet
}

const props = defineProps<Props>()
</script>

<template>
  <p :class="s.root" :lang="props.tweet.lang" dir="auto">
    <template v-for="(item, index) in props.tweet.entities" :key="index">
      <TweetLink
        v-if="item.type === 'hashtag' || item.type === 'mention' || item.type === 'url' || item.type === 'symbol'"
        :href="item.href"
      >
        {{ item.text }}
      </TweetLink>
      <template v-else-if="item.type === 'media'">
        <!-- Media text is currently never displayed, some tweets however might have indices
             that do match `display_text_range` so for those cases we ignore the content. -->
      </template>
      <template v-else>
        <!-- We use `v-html` to preserve the text encoding.
             https://github.com/vercel/react-tweet/issues/29 -->
        <span v-html="item.text" />
      </template>
    </template>
    <TweetLink v-if="props.tweet.note_tweet" :href="props.tweet.url">
      <span>&nbsp;</span>
      Show more
    </TweetLink>
  </p>
</template>

// packages/next-tweet/components/twitter-layout/tweet/tweet-body.tsx
import type { FC } from 'react'
import type {
  Indices,
  Tweet,
  HashtagEntity,
  UserMentionEntity,
  UrlEntity,
  MediaEntity,
} from 'lib/twitter/api'
import TweetLink from './tweet-link'
import s from './tweet-body.module.css'

type TextEntity = {
  indices: Indices
  type: 'text'
}

type Entity =
  | TextEntity
  | (HashtagEntity & { type: 'hashtag' })
  | (UserMentionEntity & { type: 'mention' })
  | (UrlEntity & { type: 'url' })
  | (MediaEntity & { type: 'media' })

function addEntities(
  result: Entity[],
  entities: (HashtagEntity | UserMentionEntity | MediaEntity)[],
  type: Entity['type']
) {
  for (const entity of entities) {
    for (const [i, item] of result.entries()) {
      if (
        entity.indices[0] < item.indices[0] ||
        entity.indices[1] > item.indices[1]
      ) {
        continue
      }

      const items = [{ ...entity, type }] as Entity[]

      if (item.indices[0] < entity.indices[0]) {
        items.unshift({
          indices: [item.indices[0], entity.indices[0]],
          type: 'text',
        })
      }
      if (item.indices[1] > entity.indices[1]) {
        items.push({
          indices: [entity.indices[1], item.indices[1]],
          type: 'text',
        })
      }

      result.splice(i, 1, ...items)
      break // Break out of the loop to avoid iterating over the new items
    }
  }
}

function getEntities(tweet: Tweet) {
  const result: Entity[] = [{ indices: tweet.display_text_range, type: 'text' }]

  addEntities(result, tweet.entities.hashtags, 'hashtag')
  addEntities(result, tweet.entities.user_mentions, 'mention')
  addEntities(result, tweet.entities.urls, 'url')
  if (tweet.entities.media) {
    addEntities(result, tweet.entities.media, 'media')
  }

  return result
}

const TweetBody: FC<{ tweet: Tweet }> = ({ tweet }) => {
  const entities = getEntities(tweet)

  return (
    <p className={s.root}>
      {entities.map((item, i) => {
        const text = tweet.text.slice(...item.indices)

        switch (item.type) {
          case 'hashtag':
            return (
              <TweetLink
                key={i}
                href={`https://twitter.com/hashtag/${item.text}`}
              >
                {text}
              </TweetLink>
            )
          case 'mention':
            return (
              <TweetLink
                key={i}
                href={`https://twitter.com/${item.screen_name}`}
              >
                {text}
              </TweetLink>
            )
          case 'url':
            return (
              <TweetLink key={i} href={item.expanded_url}>
                {item.display_url}
              </TweetLink>
            )
          case 'media':
            // Media text is currently never displayed, some tweets however might have indices
            // that do match `display_text_range` so for those cases we ignore the content.
            return undefined
          default:
            return <span key={i}>{text}</span>
        }
      })}
    </p>
  )
}

export default TweetBody
