// apps/vite-app/src/App.vue
<template>
  <div :class="rootClass">
    <main :class="styles.main">
      <RouterView />
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, useCssModule } from 'vue'
import clsx from 'clsx'
import { RouterView } from 'vue-router'
import './base.css'

const styles = useCssModule()

const rootClass = computed(() => clsx(styles.root, 'react-tweet-theme'))
</script>

<style module src="./layout.module.css"></style>

// apps/create-react-app/src/app.js
import clsx from 'clsx'
import { Tweet } from 'react-tweet'
import styles from './app.module.css'
import './base.css'

export default function App() {
  return (
    <div data-theme="dark">
      <div className={clsx(styles.root, 'react-tweet-theme')}>
        <main className={styles.main}>
          <Tweet id="1628832338187636740" />
        </main>
        <footer className={styles.footer}>
          <p>🤯 This tweet was statically generated.</p>
        </footer>
      </div>
    </div>
  )
}
