// packages/react-tweet/src/twitter-theme/highlighted-label.tsx
import clsx from 'clsx'
import type { TweetUser } from '../api/index.js'
import styles from './highlighted-label.module.css'

type Props = {
  user: TweetUser
  className?: string
}

export const HighlightedLabel = ({ user, className }: Props) => {
  const label = user.highlighted_label
  if (!label) return null

  const url = label.badge?.url
  if (!url) return null

  return (
    <div className={clsx(styles.label, className)}>
      <img src={url} alt={label.description} />
    </div>
  )
}

// packages/vue-better-tweet/src/twitter-theme/highlighted-label.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { TweetUser } from 'react-tweet/api'
import clsx from 'clsx'
import styles from './highlighted-label.module.css'

type Props = {
  user: TweetUser
}

const props = defineProps<Props>()

const label = computed(() => props.user.highlighted_label)
const labelUrl = computed(() => label.value?.badge?.url)
</script>

<template>
  <div v-if="label && labelUrl" :class="clsx(styles.label)">
    <img :src="labelUrl" :alt="label.description" />
  </div>
</template>
