// packages/react-tweet/src/tweet-not-found.tsx
import type { Locales } from './locales.js'
import { TweetContainer } from './tweet-container.js'
import styles from './tweet-not-found.module.css'

type Props = {
  error?: any
  locales: Locales['notFound']
}

export const TweetNotFound = ({ error, locales }: Props) => (
  <TweetContainer>
    <div className={styles.root}>
      <h3>{locales.heading(error)}</h3>
      <p>{locales.text(error)}</p>
    </div>
  </TweetContainer>
)

// packages/vue-better-tweet/src/twitter-theme/tweet-not-found.vue
<script setup lang="ts">
import TweetContainer from './tweet-container.vue'
import styles from './tweet-not-found.module.css'

type Props = {
  error?: unknown
}

defineProps<Props>()
</script>

<template>
  <TweetContainer>
    <div :class="styles.root">
      <h3>Tweet not found</h3>
      <p>The embedded tweet could not be found…</p>
    </div>
  </TweetContainer>
</template>
