// packages/next-tweet/src/tweet-info-created-at.tsx
'use client'

import type { FC } from 'react'
import format from 'date-fns/format'
import type { Tweet } from './api'
import { getTweetUrl } from './utils'
import useMounted from './lib/use-mounted'
import s from './tweet-info-created-at.module.css'

export const TweetInfoCreatedAt: FC<{ tweet: Tweet }> = ({ tweet }) => {
  const mounted = useMounted()
  const createdAt =
    typeof window !== 'undefined' && mounted ? new Date(tweet.created_at) : null

  return !createdAt ? null : (
    <a
      className={s.root}
      href={getTweetUrl(tweet)}
      target="_blank"
      rel="noopener noreferrer"
      aria-label={format(createdAt, 'h:mm a · MMM d, y')}
    >
      <time dateTime={createdAt.toISOString()}>
        {format(createdAt, 'h:mm a · MMM d, y')}
      </time>
    </a>
  )
}

// packages/vue-better-tweet/src/twitter-theme/tweet-info-created-at.vue
<script setup lang="ts">
import type { EnrichedTweet } from 'react-tweet'
import { computed } from 'vue'
import { formatDate } from 'react-tweet'
import s from './tweet-info-created-at.module.css'

type Props = {
  tweet: EnrichedTweet
}

const props = defineProps<Props>()
const createdAt = computed(() => new Date(props.tweet.created_at))
const formattedCreatedAtDate = computed(() => formatDate(createdAt.value))
</script>

<template>
  <a
    :class="s.root"
    :href="props.tweet.url"
    target="_blank"
    rel="noopener noreferrer"
    :aria-label="formattedCreatedAtDate"
  >
    <time :dateTime="createdAt.toISOString()">{{ formattedCreatedAtDate }}</time>
  </a>
</template>
