// packages/react-tweet/src/twitter-theme/tweet-in-reply-to.tsx
import type { EnrichedTweet } from '../utils.js'
import s from './tweet-in-reply-to.module.css'

export const TweetInReplyTo = ({ tweet }: { tweet: EnrichedTweet }) => (
  <a
    href={tweet.in_reply_to_url}
    className={s.root}
    target="_blank"
    rel="noopener noreferrer"
  >
    Replying to @{tweet.in_reply_to_screen_name}
  </a>
)

// packages/vue-better-tweet/src/twitter-theme/tweet-in-reply-to.vue
<script setup lang="ts">
import type { EnrichedTweet } from 'react-tweet'
import s from './tweet-in-reply-to.module.css'

type Props = {
  tweet: EnrichedTweet
}

const props = defineProps<Props>()
</script>

<template>
  <a :href="props.tweet.in_reply_to_url" :class="s.root" target="_blank" rel="noopener noreferrer">
    Replying to @{{ props.tweet.in_reply_to_screen_name }}
  </a>
</template>
