// packages/vue-better-tweet/src/twitter-theme/embedded-tweet.vue
<script setup lang="ts">
import type { Tweet } from 'react-tweet/api'
import type { TwitterComponents } from './types'
import { computed } from 'vue'
import TweetContainer from './tweet-container.vue'
import TweetHeader from './tweet-header.vue'
import TweetInReplyTo from './tweet-in-reply-to.vue'
import TweetBody from './tweet-body.vue'
import TweetMedia from './tweet-media.vue'
import TweetInfo from './tweet-info.vue'
import TweetActions from './tweet-actions.vue'
import TweetReplies from './tweet-replies.vue'
import { QuotedTweet } from './quoted-tweet'
import { enrichTweet } from 'react-tweet'

type Props = {
  tweet: Tweet
  components?: Omit<TwitterComponents, 'TweetNotFound'>
}

const props = defineProps<Props>()
const enrichedTweet = computed(() => enrichTweet(props.tweet))
</script>

<template>
  <TweetContainer>
    <TweetHeader :tweet="enrichedTweet" :components="props.components" />
    <TweetInReplyTo
      v-if="enrichedTweet.in_reply_to_status_id_str"
      :tweet="enrichedTweet"
    />
    <TweetBody :tweet="enrichedTweet" />
    <TweetMedia
      v-if="enrichedTweet.mediaDetails?.length"
      :tweet="enrichedTweet"
      :components="props.components"
    />
    <QuotedTweet
      v-if="enrichedTweet.quoted_tweet"
      :tweet="enrichedTweet.quoted_tweet"
      :components="props.components"
    />
    <TweetInfo :tweet="enrichedTweet" />
    <TweetActions :tweet="enrichedTweet" />
    <TweetReplies :tweet="enrichedTweet" />
  </TweetContainer>
</template>

// packages/react-tweet/src/twitter-theme/embedded-tweet.tsx
import type { Tweet } from '../api/index.js'
import type { TwitterComponents } from './types.js'
import { TweetContainer } from './tweet-container.js'
import { TweetHeader } from './tweet-header.js'
import { TweetInReplyTo } from './tweet-in-reply-to.js'
import { TweetBody } from './tweet-body.js'
import { TweetMedia } from './tweet-media.js'
import { TweetInfo } from './tweet-info.js'
import { TweetActions } from './tweet-actions.js'
import { TweetReplies } from './tweet-replies.js'

type Props = {
  tweet: Tweet
  components?: Omit<TwitterComponents, 'TweetNotFound'>
}

export const EmbeddedTweet = ({ tweet, components }: Props) => (
  <TweetContainer>
    <TweetHeader tweet={tweet} components={components} />
    {tweet.in_reply_to_status_id_str && <TweetInReplyTo tweet={tweet} />}
    <TweetBody tweet={tweet} />
    {tweet.mediaDetails?.length ? (
      <TweetMedia tweet={tweet} components={components} />
    ) : null}
    <TweetInfo tweet={tweet} />
    <TweetActions tweet={tweet} />
    <TweetReplies tweet={tweet} />
  </TweetContainer>
)
