// packages/vue-better-tweet/src/twitter-theme/verified-badge.vue
<script setup lang="ts">
import { computed, ref, shallowRef, watchEffect } from 'vue'
import type { TweetUser } from 'react-tweet/api'
import clsx from 'clsx'
import { Verified, VerifiedBusiness, VerifiedGovernment } from './icons'
import s from './verified-badge.module.css'

type Props = {
  user: TweetUser
}

const props = defineProps<Props>()

const verified = computed(() =>
  Boolean(props.user.verified || props.user.is_blue_verified || props.user.verified_type)
)

const icon = shallowRef(Verified)
const iconClassName = ref<string | undefined>(s.verifiedBlue)

watchEffect(() => {
  icon.value = Verified
  iconClassName.value = s.verifiedBlue

  if (verified.value) {
    if (!props.user.is_blue_verified) {
      iconClassName.value = s.verifiedOld
    }
    switch (props.user.verified_type) {
      case 'Government':
        icon.value = VerifiedGovernment
        iconClassName.value = s.verifiedGovernment
        break
      case 'Business':
        icon.value = VerifiedBusiness
        iconClassName.value = undefined
        break
    }
  }
})
</script>

<template>
  <div v-if="verified" :class="clsx(iconClassName)">
    <component :is="icon" />
  </div>
</template>

// packages/react-tweet/src/twitter-theme/verified-badge.tsx
import clsx from 'clsx'
import type { TweetUser } from '../api/index.js'
import {
  Verified,
  VerifiedBusiness,
  VerifiedGovernment,
} from './icons/index.js'
import s from './verified-badge.module.css'

type Props = {
  user: TweetUser
  className?: string
}

export const VerifiedBadge = ({ user, className }: Props) => {
  const verified = user.verified || user.is_blue_verified || user.verified_type
  let icon = <Verified />
  let iconClassName: string | null = s.verifiedBlue

  if (verified) {
    if (!user.is_blue_verified) {
      iconClassName = s.verifiedOld
    }
    switch (user.verified_type) {
      case 'Government':
        icon = <VerifiedGovernment />
        iconClassName = s.verifiedGovernment
        break
      case 'Business':
        icon = <VerifiedBusiness />
        iconClassName = null
        break
    }
  }

  return verified ? (
    <div className={clsx(className, iconClassName)}>{icon}</div>
  ) : null
}
